/**
 * Prometheus Metrics Exporter
 * Exposes metrics in Prometheus format
 */

import { NextRequest, NextResponse } from 'next/server';
import { getMetrics } from '@/lib/monitoring/metrics';
import { alertService } from '@/services/monitoring/alert.service';
import { logger } from '@/utils/logger';

export async function GET(req: NextRequest) {
  try {
    // Get Prometheus metrics
    const prometheusMetrics = await getMetrics();

    // Add custom metrics
    const customMetrics = [];

    // Alert metrics
    const alertStats = alertService.getAlertStats();
    customMetrics.push(
      `# HELP gatekeeper_alerts_active_total Total number of active alerts`,
      `# TYPE gatekeeper_alerts_active_total gauge`,
      `gatekeeper_alerts_active_total ${alertStats.active}`,
      '',
      `# HELP gatekeeper_alerts_by_severity Number of alerts by severity`,
      `# TYPE gatekeeper_alerts_by_severity gauge`,
      `gatekeeper_alerts_by_severity{severity="critical"} ${alertStats.bySeverity.critical}`,
      `gatekeeper_alerts_by_severity{severity="high"} ${alertStats.bySeverity.high}`,
      `gatekeeper_alerts_by_severity{severity="medium"} ${alertStats.bySeverity.medium}`,
      `gatekeeper_alerts_by_severity{severity="low"} ${alertStats.bySeverity.low}`
    );

    // System info metrics
    const now = new Date();
    customMetrics.push(
      '',
      `# HELP gatekeeper_system_info System information`,
      `# TYPE gatekeeper_system_info gauge`,
      `gatekeeper_system_info{version="1.0.0",node="${req.headers.get('host') || 'unknown'}"} 1`,
      '',
      `# HELP gatekeeper_system_start_time_seconds System start timestamp`,
      `# TYPE gatekeeper_system_start_time_seconds gauge`,
      `gatekeeper_system_start_time_seconds ${Math.floor(process.uptime())}`
    );

    // Combine all metrics
    const allMetrics = [
      '# Generated by Gatekeeper RPA Performance Monitor',
      `# Scrape time: ${now.toISOString()}`,
      '',
      prometheusMetrics,
      customMetrics.join('\n')
    ].join('\n');

    return new NextResponse(allMetrics, {
      headers: {
        'Content-Type': 'text/plain; version=0.0.4'
      }
    });

  } catch (error) {
    logger.error('Prometheus metrics export error:', error);
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to export metrics'
      },
      { status: 500 }
    );
  }
}